name: Flutter App Deploy

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [flutter_deploy]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup Flutter environment
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.0' # O la versión que estés usando

      - name: Install dependencies
        run: flutter pub get
        working-directory: ../

      # Ensamblar el proyecto Flutter en un ejecutable
      - name: Flutter Build
        run: flutter build web
        working-directory: ../
        
      # Construir la imagen Docker
      - name: Docker Build
        run: docker build -t ${{secrets.DOCKER_USER}}/flutter-app:${{github.sha}} .

      # Iniciar sesión en Docker Hub
      - name: Docker Login
        run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USER}} --password-stdin

      # Subir la imagen a Docker Hub
      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/flutter-app:${{github.sha}}

      # Notificar a Render para actualizar la imagen
      - name: Notify Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cs2e7jd6l47c73bgbrtg?key=YVOhyQomkc4" \
          -H "Content-Type: application/json"
